"""empty message

Revision ID: 616719ad6eea
Revises: bc65aa74b009
Create Date: 2025-05-24 22:48:47.123005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616719ad6eea'
down_revision = 'bc65aa74b009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('role', ['role'], unique=True)

    # ### end Alembic commands ###
